let S = {
    "testC": [
        ["*p", "u up?", 0],
        ["*p", "i wanna talk", 0],
        ["Onion", "what is it", 60],
        ["*p", "tell me about ur kind", 0],
        ["Onion", "The onion, also known as the bulb onion or common onion,", 120],
        ["Onion", "is a vegetable that is the", 60],
        ["Onion", "most widely cultivated species of the genus Allium.", 120],
        ["Onion", "The shallot is a botanical variety of the onion", 120],
        ["Onion", "which was classified as a separate species", 120],
        ["Onion", "until 2010.", 40],
        ["Onion", "Its close relatives include garlic,", 240],
        ["*p", "scallion,", 0],
        ["Onion", "leek,", 120],
        ["Onion", "and chive.", 60],
        ["Onion", "second to last text", 100],
        ["*p", "last text", 0],
    ],
    "testD": [
        ["Nagito", "hi", 150],
        ["Nagito", "hi", 60],
        ["Nagito", "hi", 40],
        ["Nagito", "hi", 40],
        ["Nagito", "hi", 60],
        ["Nagito", "hi", 60],
        ["Nagito", "hi", 10],
        ["*p", "Mukuro Ikusaba", 0],
        ["Nagito", "huh?", 120],
        ["*p", "the 16th student", 0],
        ["Nagito", "uhhhh", 60],
        ["*p", "lying hidden somewhere in this school", 0],
        ["Nagito", "what schjgol???", 90],
        ["Nagito", "*school", 30],
        ["*p", "the one they call the Ultimate Despair", 0],
        ["Nagito", ":/", 30],
        ["Nagito", "the what", 60],
        ["*p", "Watch out", 0],
        ["*p", "for her", 0],
        ["Nagito", "what ARE YOU SAYINGGGG", 120],
        ["*p", "last text", 0],
    ],
    "testChoice" : [
        ["Onion", "what is ur name?", 120],
        ["*p", "im ", 0, "testChoiceFlag", "Shrek|Donkey|Farquaad"],
        ["*p", "---", 0],
    ],
    "testChoice1" : [
        ["Onion", "Shrek?", 100],
        ["Onion", "its really u?", 60],
        ["*p", "yes. it is me", 0],
        ["*p", "last text", 0],
    ],
    "testChoice2" : [
        ["Onion", "Donkey?", 100],
        ["Onion", "you don't look like one?", 60],
        ["*p", "uhhhhhhh", 0],
        ["*p", "last text", 0],
    ],
    "testChoice3" : [
        ["Onion", "Farquaad?", 100],
        ["Onion", "what kind of name is that?", 150],
        ["Onion", "lol it", 100],
        ["Onion", "it sounds like", 60],
        ["Onion", "nvm", 300],
        ["*p", "wow rude ok", 0],
        ["*p", "last text", 0],
    ],
    "testE": [
        ["Weeb", "yo", 10],
        ["*p", "eeeeee", 0],
        ["*p", "", 0, "testE1", "hey|nice pfp you got there"],
        ["*p", "-", 0],
    ],
    "testE1A": [
        ["Weeb", "what's up", 400],
        ["Weeb", "i hear you're a pretty little guy", 100],
        ["*p", "uhhhh", 0],
        ["*p", "what", 0],
        ["*p", "never been called that before", 0],
        ["*p", "last text", 0]
    ],
    "testE1B": [
        ["Weeb", "thanks", 400],
        ["Weeb", "it's quite poggers huh", 60],
        ["*p", "yes, it is so poggers bb", 0],
        ["*p", "last text", 0],
    ],
    "momMorningOne":[
        ["Mom","Hi Honey! Are you ready for your first day of work?"],
        ["Player","I'm [nervous/anxious/worried]"],
        ["Mom","Afraid you'll fall in love? You know I want grandbabies, so that wouldn't be too bad ;)"],
        ["Mom","What for? You've always been a killer with women, men, and more. I'm sure you'll do fine and maybe bring home some grandbabies ;)"],
        ["Mom","There's no need to worry, all the people you flirt with will be sure to have someone to show them a good time, and there's no way they'll know it was you. Wish it was you so I could get some grandbabies ;)        "],
        ["Player","Okay mom. I've gotta go ttyl."],
        ["Mom","Break some hearts!! <3 <3"],
    ],
    "BFFMorningOne":[
        ["BFF","Hey Hey, ready for the first day? Still not 100% sure what you do at that job."],
        ["Player","As far as I know, I set up dates, to not go on them."],
        ["BFF","To *not* go on them?"],
        ["Player","To NOT go on them…"],
        ["BFF","I still don't get it, but if it pays rent it pays rent. Beats farming that's for sure."],
        ["BFF","Don't think I haven't noticed you dodging my question."],
        ["Player","I'm [Ready/Not Ready]"],
        ["BFF","Good to hear. Well I hope it goes well. Don't fall in love haha."],
        ["Player","Not planning on it…"],
        ["BFF","Ready: I'm sure you'll do fine. And hey, that rent isn't gonna earn itself. So get out there and give 'em the goods, big shooter"],
        ["Player","Great encouragement as always."],
    ],
    "d1_kcA": [
        ["kc", "hi there ...", 10],
        ["kc", "i'm you're supervisor, Karan Chandrashekar.", 120],
        ["kc", "you can call me Christopher.", 120],
        ["kc", "this is our chat system that we use, Discharge...", 200],
        ["kc", "just need to type into the chat bar, to send message.", 120],
        ["*p", "Hello. Nice to meet you.", 0],
        ["*p", "last text", 0],

    ],
    "d1_kcAtest": [
        ["kc", "hi there ...", 10],
        ["kc", "i'm you're supervisor, Karan Chandrashekar.", 120],
        ["kc", "you can call me Christopher.", 120],
        ["kc", "this is our chat system that we use, Discharge...", 200],
        ["kc", "just need to type into the chat bar, to send message.", 120],
        ["*t", "It's not that hard...", 0],
        ["kc", "Some more text idk...", 120],
        ["*p", "Nice to meet you", 0],
        ["*p", "last text", 0],

    ],
    "d1_nkA" : [
        ["nk", "Hey, I'm Nidia from payroll.", 1000],
        ["nk", "I will be sending you commission via proxy account", 120],
        ["nk", "through Netherlands.", 0],
        ["nk", "At the rate of approximately 10~20$ per customer, plus tip.", 150],
        ["*p", "last text", 0],

    ],
}