let S = {

    "d1_kcA": [
        ["kc", "hi there ...", 10],
        ["kc", "i'm you're supervisor, Karan Chandrashekar here at The Wing.", 240],
        ["kc", "but please call me Christopher.", 120],
        ["kc", "this is our chat system that we use, Discharge...", 180],
        ["kc", "just need to type into the chat bar, to send me message.", 180],
        ["*p", "hello. nice to meet you.", 0],
        ["kc", "good job. u sent your first message.", 240],
        ["*t", "it wasn't that hard,,,", 100],
        ["kc", "soon, you should get a message from Nadine… our.", 180],
        ["kc", "payroll manager.", 0],
        ["kc", "you will be using the left sidebar to switch the users. just click.", 180, "sentFirstMessageKaran"],
        ["*w", "", 0],
    ],
    "d1_nkA" : [
        ["nk", "Hey, I'm Nidia from payroll.", 400],
        ["*t", "I thought your name was Nadine…", 100],
        ["nk", "I will be sending you commission via proxy account", 300],
        ["nk", "through Netherlands.", 0],
        ["nk", "At the rate of approximately 30~40$ per customer, plus tip.", 300],
        ["*p", "hello. nice to meet you.", 0, "sentFirstMessageNidia"],
        ["nk", "Nice to meet you too, Indigo🙂.", 300],
	    ["*p", "uh,, is that all i need to know?", 0],
        ["nk", "Yes.", 120], 
        ["nk", "Hopefully, I have a payment for you soon 😄.", 300],
        ["*t", "a little stiff… but they seem nice?", 100],
        ["*w", "", 0],
    ],
    "d1_kcB" : [
        ["kc", "ok… seems like you figured that out.", 350],
        ["*p", "yeah, i've got it so far.", 0],
        ["kc", "let me explain to you what we do here at The Wing.", 250],
        ["kc", "many people use Discharge for dating but...", 250],
        ["kc", "lot of people are... unsuccessful.", 150],
        ["kc", "some of those people have enough money to hire us to help them.", 300],
        ["kc", "we have special framework that will let you, our employee", 400],
        ["kc", "pretend to be our clients in order to get them dates", 0],
        ["*p", "i see", 0],
        ["kc", "we isolated you as a candidate because of your charisma", 200],
        ["kc", "so it's up to you what to say to clients.", 200],
        ["*p", "", 0, "choiceTutorial", "charisma?|up to me?"],
        ["kc", "you were really good in the interview.", 400],
        ["kc", "and you're english is excellent!", 120, "finishedTutorial"],
        ["kc", "nothing to worry about.", 100],
        ["kc", "i will send you your first client in a little while.", 200],
        ["kc", "take some time to get ready. good luck", 200],
        ["*w", "", 0],
    ],
    "d1_mA" : [
        ["m", "Is thiss/??", 600],
        ["m", "How y ou use this thing?/??", 450],
        ["m", "Hello???", 200],
        ["*p", "yes? you're doing just fine", 0],
        ["*p", "hi mom", 0],
        ["m", "I do n't know... why we can't just use WhatsApp??", 400],
        ["*p", "they both work the same way, this is just easier for me.", 0],
        ["m", "WELL...🥺🥺🥺", 200],
        ["m", " I just wanted to tell you good luc k for your first day at work!💖", 400],
        ["m", "But I also wanted to remind you to think about the future…",400],
        ["m", "Do you remember what we discuss ed 😉😉😉?", 200],
        ["*t", "she’s on about this again, why can’t we just be normal for once?", 150],
        ["*p", "yeah,,", 0],
        ["*p", "i remember, i just", 0],
        ["*p", "i just want to focus for today.", 0],
        ["*p", "this is really important to me.", 0],
        ["*p", "i need to make a good impression so...", 0],
        ["*p", "i don’t want to think about anything unrelated at the moment", 0, "finishedFirstConvoMom"],
        ["m", "Just keep it in mind. You know your dad and I aren’t getting any", 1000],
        ["m", "younger, and I’m sure you can make some time to think it over.", 0],
        ["*t", "…does that really matter…? i can’t do this right now.", 100],
        ["*t", "although, she'd be more annoying though if she knew what my", 100],
        ["*t", "job actually was", 0],
        ["*p", "i will mom. i have to go get ready now, sorry.", 0],
        ["*p", "", 0, "", "bye|talk to you later"],
        ["*p", "love you", 0],
        ["m", "Love you more ❤️❤️❤️ !!", 600],
        ["*w", "", 0],
    ], 
    
    "d1_fA" : [
        ["f", "hey ! how’s everything ?", 100],
        ["f", "did you manage to snag that job you kept talking to me about lol", 120],
        ["f", "it’s kind of funny how excited you were about it", 150],
        ["f", "even though its pretty sketchy", 100],
        ["f", "they don’t make you take an oath of silence or smth right ?", 250],
        ["*p", "oh yeah, i did", 0],
        ["*p", "i can’t believe i didn’t tell you...", 0],
        ["*p", "today’s actually the first day", 0],
        ["*p", "so i can’t talk for long.", 0],
        ["*p", "but thanks for checking up on me,,", 0],
        ["*p", "it’s not that sketchy i dont think,,", 0],
        ["*p", "is it?", 0],
        ["*p", "i havent ever heard of a job like this but they havent been weird", 0],
        ["*p", "yet,,,", 0],
        ["f", "that’s your first clue that its strange", 120],
        ["f", "why haven’t we heard about anything like this if its not sketchy ?", 120],
        ["f", "we are... terminally online lol", 150],
        ["f", "i just want you to be careful, this could be dangerous.", 250],
        ["*t", "…", 120],
        ["*t", "i guess they’re not wrong, i should be more careful", 250],
        ["f", "anyway i didn’t really mean to scare you,", 150],
        ["f", "even if its a little weird i trust your judgement", 100],
        ["f", "hoping you have a good day today ! kick ass out there !", 250],
        ["f", "i gotta get going too", 250],
        ["f", "my partner wanted to go out for breakfast today and", 250],
        ["f", "i woke up late lol", 0],
        ["*p", "thanks.. i really appreciate it.", 0, "finishedFirstConvoFriend"],
        ["*t", "since mom is being so annoying right now", 120],
        ["*p", "i’ll do my best! see you,, and have fun,,", 0],
        ["*w", "", 0]
    ],

    "d1_kcC" : [
        ["kc", "the system is ready now. i am ready to send you your first client", 300], 
        ["kc", "good luck.", 100, "sendFirstClient"], 
        ["*p", "thank you.", 0],
        ["*w", "", 0],
    ], 

    "d1_fjA" : [
        ["fj", "Hello?", 100], 
        ["fj", "I am FELIX JOEL.", 120], 
        ["*p", "This is The Wing. How may I help you?", 0],
        ["fj", "So...", 80],
        ["fj", "There's this girl :)", 80],
        ["fj", "And", 40],
        ["fj", "I", 20],
        ["fj", "CANNOT mess this up.", 80],
        ["*p", "", 0, "", "What's her name?|Could you elaborate?", 0],
        ["fj", "T R I S H she's so pretty and nice and I can't", 180],
        ["fj", "I can't stop THINKING about her!!", 100],
        ["fj", "I've already submitted her account and stuff, so... you got", 240],
        ["fj", "that already", 0],
        ["*p", "What does she like? Any other information you could give me?", 0], 
        ["fj", "Huhhhh...", 140],
        ["fj", "That's a hard one, Wing.", 200],
        ["fj", "She's so quiet all the time.", 120],
        ["fj", "Uhh...", 60],
        ["fj", "I'm a coffee man myself but I'm pretty sure she likes tea.", 120],
        ["fj", "Also, she's really shy, so talk about interests first! not LOOKS!", 120], 
        ["fj", "That's all I got.", 180],
        ["fj", "Keep me posted, Wing", 60, "finishedFirstConvoFelix"],
        ["*p", "Understood.", 0],
        ["*w", "", 0],
    ],
    "d1_fjB1" : [
        ["fj", "Oh..... also one more thing!", 200],
        ["fj", "PLEASE", 100],
        ["fj", "please please please", 100],
        ["fj", "don't lie to her", 100],
        ["fj", "like i know this,, whole... Wingy thing is lying but", 240],
        ["fj", "that's for a GOOD reason!", 100],
        ["fj", "I would really like to start with no lies...!", 100],
        ["*t", "uhh... you tell me this now...?", 100],
        ["*p", "Okay, I will keep that in mind.", 0, "d1_fjB1_talkedtoFelix"],
        ["*t", "you better not give me any more conditions, Felix...", 100],
        ["fj", "be cautious, Wing. she's very hesitant", 300],
        ["fj", "you're the pro though, i'm sure you're handling it just fine.", 100],
        ["*w", "", 0],
    ],
    "d1_fj_tpFail" : [
        ["fj", "NOOOOOOoooooooo", 200],
        ["fj", "No...", 60],
        ["fj", "This can't be happening...", 100],
        ["fj", "I believed in you, Wing...", 100],
        ["fj", "I thought you were a pro", 100],
        ["*t", "that's something i'm definitely not", 100],
        ["*p", "My sincerest apologies, is there another date I can help you with?", 0],
        ["fj", "No...  you don't understand!!", 100],
        ["fj", "Wing, my life is OVER.", 100],
        ["*t", "yikes,,", 100],
        ["fj", "You don't know how lonely it is not having someone,", 100],
        ["*t", "it's quite alright dude,, you're not gonna die", 100],
        ["*p", "The Wing does not offer a guarantee. Sorry Felix.", 0],
        ["fj", "ugggghhhhhhh,", 100],
        ["fj", "would YOU date me, Wing?", 240],
        ["fj", "Please please please, I'm a nice guy I swear?", 100],
        ["*t", "excuse me what", 100],
        ["*t", "get a hobby man", 100],
        ["*p", "As The Wing, I'm not able to do that.", 0],
        ["fj", "Just leave me! Hereupon I shall live forever alone", 150],
        ["*p", "We hope to see you again, Felix.", 0, "d1_end"],
        ["*t", "We really don't...", 100],
        ["*w", "", 0],
    ],
    "d1_fj_tpSuccessA" : [
        ["fj", "OH MY GOSH oh my gosh oH m Y G O sh.", 240],
        ["fj", "omg.", 60],
        ["fj", "You did it, Wing!!", 60],
        ["fj", "I'm so happy right now.", 100],
        ["fj", "So, what did you land for me? What's the venue?", 240],
        ["*p", "You're both going to Barstucks.", 0],
        ["fj", "Blech!", 240],
        ["fj", "I know I should be thankful but this... is heresy!", 240],
        ["fj", "A man with exquisite tastes such as myself going to", 190],
        ["fj", "B A R S T U C K S ...", 60], //barstucks
        ["*t", "yikes,,, this guy...", 100],
        ["*p", "Sorry about that.", 0],
        ["*p", "We can offer a partial refund.", 0],
        ["fj", "No. IT'S ACTUALLY PERFECT!!", 100],
        ["fj", "I can demonstrate my exquisite taste!", 100],
        ["*t", "yeah, cause it's just so attractive...", 100],
        ["fj", "I love it. Thank you, Ms. Wing...", 100],
        ["fj", "Mr. Wing? Your Wingyness?", 240],
        ["*t", "just leave it,,"]
        ["fj", "I'll update you on how the date goes... Professor Wing", 240],
        ["*t", "please don't,,"]
        ["*p", "We hope to see you again, Felix.", 0, "d1_end"],
        ["*t", "i'm actually gonna hear from him again... aren't I?", 100],
        ["*t", "damn customer service,,,", 100],
        ["*w", "", 0],
    ],
    "d1_fj_tpSuccessB" : [
        ["fj", "OH MY GOSH oh my gosh oH m Y G O sh.", 240],
        ["fj", "omg.", 60],
        ["fj", "You did it, Wing!!", 60],
        ["fj", "I'm so happy right now.", 100],
        ["fj", "So, what did you land for me? What's the venue?", 240],
        ["*p", "You're both going to a cafe called Midnight Teashop.", 0],
        ["fj", "OOOOOOOOoooooooo", 60],
        ["fj", "You really are a pro! Was that her reccomendation?", 180],
        ["*p", "I said you liked coffee, and so she wanted you to try dirty chai", 0],
        ["fj", "OMG... you're a dirty little chai aren't you, Wing?", 180],
        ["*t", "sorry, what ._.", 100],
        ["fj", "ACk.... everytime I try jokes like 'normal people'", 400],
        ["fj", "It just comes out weirdchamp.", 100],
        ["*t", "honestly relateable", 100],
        ["fj", "Anyway, this is really nice! I'm proud to call you my wing.", 240],
        ["*t", "???", 100],
        ["*p", "We hope to see you again, Felix.", 0, "d1_end"],
        ["*w", "", 0],
    ],
    "d1_fj_tpSuccessC" : [
        ["fj", "OH MY GOSH oh my gosh oH m Y G O sh.", 240],
        ["fj", "omg.", 60],
        ["fj", "You did it, Wing!!", 60],
        ["fj", "I'm so happy right now.", 100],
        ["fj", "So, what did you land for me? What's the venue?", 240],
        ["*p", "It's just a video call, but it's a date.", 0],
        ["fj", "Aww...", 60],
        ["fj", "It's something I guess.", 60],
        ["*p", "Do you have a 'french press', by the way?,", 0],
        ["fj", "Yes, 34.", 60],
        ["*t", "why am i not surprised...", 100],
        ["*p", "Well, she wants to teach you to make tea in a french press.", 0],
        ["fj", "WHAAAAAT?", 60],
        ["fj", "THAT's ACTUALLY so COOL!!", 100],
        ["fj", "You're a genius, Wing!", 100],
        ["fj", "She'll love seeing my french press collection!", 240],
        ["*t", "all thirty-four of them,,", 100],
        ["*t", "at least he's happy though.", 100],
        ["*p", "We hope to see you again, Felix.", 0, "d1_end"],
        ["*w", "", 0],
    ],
    "d1_tpA" : [
        ["*p", "hey there.", 0],
        ["tp", "hi.", 300],
        ["*p", "your profile says you like tea.", 0],
        ["*p", "", 0, "tpA_openingLine", "tell me about it|i think you're beauTEAful."],
        ["*w", "", 0],
    ],
   
    "d1_tpB0" : [
        ["tp", "yikes.", 300, "tpFail",],
        ["*b", "", 60],
    ],
   
    "d1_tpB1" : [
        ["tp", "oh, I'd love to.", 300,],
        ["tp", "idk i wouldn't say im an expert but", 140],
        ["tp", "hehe what can i tell you about?", 140],
        ["*p", "i really like ", 0, "d1_tpB1_choiceCoffeeTea", "coffee|tea"],
        ["*w", "", 0],
    ],
    "d1_tpC1" : [
        ["*p", "so, what tea do you think i'd like?", 300,],
        ["tp", "it really depends what kind of coffee you like ;;", 240],
        ["tp", "but maybe black tea?", 140],
        ["tp", "...or maybe", 300],
        ["tp", "some cafes they do this thing... called a dirty chai", 240],
        ["tp", "it's like...a indian chai with a shot of espresso", 140],
        ["*p", "oh?", 0],
        ["*p", "", 0, "d1_tpC1_choiceLocation", "can you get that at Barstucks?|any cafe you recommend?"],
        ["*w", "", 0],
    ],
    "d1_tpC2" : [
        ["tp", "oh?", 140],
        ["tp", "what kind?", 140],
        ["*p", "uh...", 0, "", "green|boba|chai"],
        ["tp", "real convincing with the coffee pfp.", 240],
        ["tp", "jk jk", 100],
        ["tp", "but im a little wary cause", 100],
        ["tp", "there's people who'll just say whatever for the date.", 150],
        ["*p", "ah, yeah, makes sense.", 0], 
        ["*p", "i actually really like ", 0, "d1_tpC2_choiceAssertion", "coffee|tea"],
        ["*w", "", 0],
    ],
    "d1_tpD1" : [
        ["tp", "Barstucks?", 100],
        ["tp", "self-proclaimed coffee liker enjoys Barstucks?", 240],
        ["*p", "", 0, "", "yeah, and what of it?|ah, sorry you're right"],
        ["tp", "dw dw just messing with u.", 240],
        ["tp", "but no, ofc you couldn't get it there.", 240],
        ["*p", "oh", 0],
        ["tp", "you want to take me to Barstucks?", 300],
        ["*p", "", 0, "d1_tpD1_choiceBarstucks", "definitely!|uh... sure|hmm..."],
        ["*w", "", 0,]
    ],
    "d1_tpD2" : [
        ["tp", "ahhh... gotcha.", 240], 
        ["tp", "maybe I could fix you lol", 210],
        ["*p", "", 0, "d1_tpD2_choiceDate", "on... a date ;)?|i'm open to it :)"],
        ["*w", "", 0],
    ],
    "d1_tpD3" : [
        ["tp", "cool.", 240],
        ["tp", "you're passionate about tea, like me :)", 300, "d1_tpD3_liedToTrish"],
        ["*p", "yeah", 0],
        ["*w", "", 0],
    ],
    
    "d1_tpE1": [
        ["tp", "uhh...", 150],
        ["tp", "forgive me, you're probably a really nice guy but", 240], 
        ["tp", "a little too eager idk", 240], 
        ["*t", "ah shoot", 100],
        ["tp", "let's just shelve this one, okay?", 240], 
        ["tp", "nice meeting you?", 240],
        ["*p", "sure. nice meeting you too.", 0, "tpFail"],
        ["*w", "", 0],
    ],   
    "d1_tpE2" : [
        ["tp", "sounds kinda lame lol", 200],
        ["*p", "", 0, "", "ouch|ah, sorry"],
        ["tp", "no no, in kind of a cute way", 200],
        ["tp", "skskskgs i mean... i'd refuse but", 400],
        ["tp", "there's something about how dumb this is", 200], 
        ["*p", "wow", 0],
        ["tp", "im serious!!", 100],
        ["tp", "you're being so chill about it too", 200], 
        ["tp", "let's do it.", 100],
        ["*t", "is this...what 'normal' people are like...?", 100],
        ["*p", "im down", 0],
        ["tp", "Meet you there... Sunday at 3?", 300],
        ["*p", "wouldn't miss it :)", 0, "tpA"],
        ["*w", "", 0],
    ],
    "d1_tpE3" : [
        ["*p", "do you have a favorite cafe?", 0],
        ["tp", "wow hmmm", 240],
        ["tp", "actually yes", 500],
        ["tp", "it's a little pricey and a little rundown, but i'll help u order :)", 240],
        ["tp", "im actually excited about this skskfsks", 100],
        ["tp", "you don't find people on here who are... actually genuine", 300],
        ["tp", "not just thirsty for the date.", 150], 
        ["*t", "'genuine',,, that kinda hurts, sorry Trish", 100],
        ["*p", "haha, yeah.", 0],
        ["tp", "look up Midnight Teashop, you'll find it. Meet you there... Sunday at 3?", 300],
        ["*p", "wouldn't miss it :)", 0, "tpSuccessB"],
        ["*w", "", 0],
    ],
    "d1_tpE4" : [
        ["tp", "something wrong?", 100],
        ["*t", "i gotta fix this somehow,,,", 100],
        ["*p", "i was just thinking", 0],
        ["*p", "i do like tea but", 0],
        ["*p", "i'm ", 0, "d1_tpE4_aboutTea", "not THAT knowledgeable|thinking i'd like to learn from u ;)"],
        ["*w", "", 0],
    ],
    "d1_tpF1" : [
        ["tp", "ah, i see", 300],
        ["*p", "i really like tea from cafes, but i don't really brew it myself.", 0],
        ["*p", "i only know how to brew coffee.", 0],
        ["tp", "oh?", 100],
        ["tp", "well, do you have a french press?", 100],
        ["*t", "how should i know,, uh,,,", 100],
        ["*p", "yes, ofc", 0],
        ["tp", "you can make outstanding tea in there :)", 240],
        ["*p", "maybe ", 0, "d1_tpF1_choiceDate", "u could come over|we can vc sometime"],
        ["*w", "", 0],
    ],
    "d1_tpG1" : [
        ["tp", "sure. sounds fun.", 300],
        ["tp", "you free Sunday, afternoonish?", 300],
        ["*p", "wouldn't miss it :)", 0, "tpSuccessC"],
        ["*w", "", 0],
    ],

    "d1_nk_tpFail" : [
        ["nk", "Hello Indigo.", 300],
        ["nk", "Looks like you failed to get the date with Trish Price.", 240],
        ["nk", "Hard luck.", 100],
        ["nk", "You don't make any comission on this one.", 240],
        ["nk", "The client has been notified.", 240, "tpDebrief"],
        ["*p", "Sorry about that.", 0], 
        ["*w", "", 0]
    ],
    "d1_nk_tpSuccess" : [
        ["nk", "Hello Indigo.", 300],
        ["nk", "Looks like you matched with Trish Price.", 240],
        ["nk", "You made 35$. Well done. You will recieve at weekend.", 240],
        ["nk", "Thank you.", 0],
        ["nk", "The client has been notified.", 240, "tpDebrief"],
        ["*w", "", 0],
    ],
    

    "d1_mB" : [ 
        ["m", "Hello, I just wanted to check up on you", 100],
["m", "after your first day.", 60],
["m", "Am I too early?", 60],
 
["*p", "no, no, now is fine.", 0],
 
["m", "So how was it?", 100],
	
	["*p", "well, you know", 0],
["*p", "I think it went ok.", 0],
	["*p", "everyone was nice.", 0],

["*t", "that’s not a complete lie i guess.", 100],
 
["m", "I see.", 100],
["m", "You really won’t tell me any details?", 100],

["*p", "i want to, but i’m not sure if my boss would be happy about it.", 0],
	["*p", "i’m dealing with people personally, so...", 0],

["*t", "a likely excuse, i should just be honest sooner or later ", 100],

["m", "You should really be able to tell everything to your own Mother.", 100],

	["*p", "it’s not my control, im sorry", 0],

["m", "If you say so,", 100],
["m", "I also wanted to talk about your future", 100],

	["*t", "oh no.", 100],

	["m", "About meeting someone, like me and your dad", 100],

["*p", "Oh. That.", 0],

	["*t", "it’s not like i didnt see this coming.", 100],
["*t", "it’s usually normal for people like me ", 100],

["m", "Yes? That.", 100],
 
["*p", "i think that’s something", 0],
	["*p", "i’m too busy for at the moment", 0],

["*t", "stay cool, just speak normally.", 100],

	["m", "I know you're busy,", 100],
	["m", "but that's something you have to make time for eventually.", 100],
	["m", "Some things are more important than work.", 100],

	["*p", "yes, im aware.", 0],

	["*t", "i just dont think this is important to me at all", 100],
	
	["*p", "i'll think it over,", 0],
["*p", "since you're so adamant about it.", 0],

["m", "Okay, I'm glad you're finally listening to me", 100],

	["*t", ".....", 100],
["*t", "is this really what i want? is this how it should end,,", 100],
	["*t", "...", 100],
	["*t", "no", 100],
	["*t", "this isn't right", 100],
	["*t", "i never, never say what i want", 100],
	["*t", "whether its in this job", 100],
	["*t", "or to everyone i care about", 100],
	["*t", "...", 100],
	["*t", "let me be honest,, for once,", 100],

	["*p", "Actually.. i need to tell you something", 0],

	["m", "?", 100],
	["m", "What is it?", 100],
	
["*t", "...", 100],
	["*t", "deep breaths", 100],

	["*p", "so ive come to realize", 0],
	["*p", "that i just dont want the same things that you want", 0],
	["*p", "i dont want to get married,", 0],
	["*p", "or involved with someone at all", 0],
	["*p", "i dont understand it", 0],
	["*p", "even though ive tried really hard to", 0],
	["*p", "and i want to stop pretending that i do", 0],
	["*p", "taking on this job made me realize", 0],
	["*p", "how exhausting it is to pretend", 0],
	["*p", "how long ive been pretending", 0],
	["*p", "and i dont want to do that anymore", 0],
	["*p", "i would appreciate if you would respect my wishes", 0],
	["*p", "and not push it any further", 0],
	
["m", "...", 100],
	["m", "So that's what it was.", 100],
	["m", "I had the feeling that you weren't yourself lately.", 100],
	["m", "This is a lot to take in so suddenly.", 180],
	["m", "If you were feeling like this why didn't you say anything?", 180],	
	["*p", "because i was ", 0, "", "afraid|afraid"],
	["*p", "i was so afraid,", 0],	
	["*p", "and i tried to ignore the feeling that something was wrong", 0],
	["*p", "but the more i try, the worse it gets", 0],
	["*p", "i shouldnt have lied for so long", 0],
	
["m", "...", 100],
	["m", "I am trying to grasp this fully.", 100],
	["m", "I'm sorry it might take some time", 100],
	["m", "We'll need to talk about it together some more", 100],
	["m", "Can you come visit us?", 100],
	["m", "I think we have a lot to talk about.", 100],
	
	["*t", "...", 100],
["*t", "i guess we do", 100, "END"],
        ["*w", "", 0]

    ]
    
    
}