let S = {

    "d1_kcA": [
        ["kc", "hi there ...", 10],
        ["kc", "i'm you're supervisor, Karan Chandrashekar here at The Wing.", 240],
        ["kc", "but please call me Christopher.", 120],
        ["kc", "this is our chat system that we use, Discharge...", 180],
        ["kc", "just need to type into the chat bar, to send me message.", 180],
        ["*p", "hello. nice to meet you.", 0],
        ["kc", "good job. u sent your first message.", 240],
        ["*t", "it wasn't that hard,,,", 100],
        ["kc", "soon, you should get a message from Nadine… our.", 180],
        ["kc", "payroll manager.", 0],
        ["kc", "you will be using the left sidebar to switch the users. just click.", 180, "sentFirstMessageKaran"],
        ["*w", "", 0],
    ],
    "d1_nkA" : [
        ["nk", "Hey, I'm Nidia from payroll.", 400],
        ["*t", "I thought your name was Nadine…", 100],
        ["nk", "I will be sending you commission via proxy account", 300],
        ["nk", "through Netherlands.", 0],
        ["nk", "At the rate of approximately 30~40$ per customer, plus tip.", 300],
        ["*p", "hello. nice to meet you.", 0, "sentFirstMessageNidia"],
        ["nk", "Nice to meet you too, Indigo🙂.", 300],
	    ["*p", "uh,, is that all i need to know?", 0],
        ["nk", "Yes.", 120], 
        ["nk", "Hopefully, I have a payment for you soon 😄.", 300],
        ["*t", "a little stiff… but they seem nice?", 100],
        ["*w", "", 0],
    ],
    "d1_kcB" : [
        ["kc", "ok… seems like you figured that out.", 350],
        ["*p", "yeah, i've got it so far.", 0],
        ["kc", "let me explain to you what we do here at The Wing.", 250],
        ["kc", "many people use Discharge for dating but...", 250],
        ["kc", "lot of people are... unsuccessful.", 150],
        ["kc", "some of those people have enough money to hire us to help them.", 300],
        ["kc", "we have special framework that will let you, our employee", 400],
        ["kc", "pretend to be our clients in order to get them dates", 0],
        ["*p", "i see", 0],
        ["kc", "we isolated you as a candidate because of your charisma", 200],
        ["kc", "so it's up to you what to say to clients.", 200],
        ["*p", "", 0, "choiceTutorial", "charisma?|up to me?"],
        ["kc", "you were really good in the interview.", 400],
        ["kc", "and you're english is excellent!", 120, "finishedTutorial"],
        ["kc", "nothing to worry about.", 100],
        ["kc", "i will send you your first client in a little while.", 200],
        ["kc", "take some time to get ready. good luck", 200],
        ["*w", "", 0],
    ],
    "d1_mA" : [
        ["m", "Is thiss/??", 600],
        ["m", "How y ou use this thing?/??", 450],
        ["m", "Hello???", 200],
        ["*p", "yes? you're doing just fine", 0],
        ["*p", "hi mom", 0],
        ["m", "I do n't know... why we can't just use WhatsApp??", 400],
        ["*p", "they both work the same way, this is just easier for me.", 0],
        ["m", "WELL...🥺🥺🥺", 200],
        ["m", " I just wanted to tell you good luc k for your first day at work!💖", 400],
        ["m", "But I also wanted to remind you to think about the future…",400],
        ["m", "Do you remember what we discuss ed 😉😉😉?", 200],
        ["*t", "she’s on about this again, why can’t we just be normal for once?", 150],
        ["*p", "yeah,,", 0],
        ["*p", "i remember, i just", 0],
        ["*p", "i just want to focus for today.", 0],
        ["*p", "this is really important to me.", 0],
        ["*p", "i need to make a good impression so...", 0],
        ["*p", "i don’t want to think about anything unrelated at the moment", 0, "finishedFirstConvoMom"],
        ["m", "Just keep it in mind. You know your dad and I aren’t getting any", 1000],
        ["m", "younger, and I’m sure you can make some time to think it over.", 0],
        ["*t", "…does that really matter…? i can’t do this right now.", 200],
        ["*t", "although, she'd be more annoying though if she knew what my", 0],
        ["*t", "job actually was", 0],
        ["*p", "i will mom. i have to go get ready now, sorry.", 0],
        ["*p", "", 0, "", "bye|talk to you later"],
        ["*p", "love you", 0],
        ["m", "Love you more ❤️❤️❤️ !!", 600],
        ["*w", "", 0],
    ], 
    
    "d1_fA" : [
        ["f", "hey ! how’s everything ?", 0],
        ["f", "did you manage to snag that job you kept talking to me about lol", 120],
        ["f", "it’s kind of funny how excited you were about it", 150],
        ["f", "even though its pretty sketchy", 100],
        ["f", "they don’t make you take an oath of silence or smth right ?", 250],
        ["*p", "oh yeah, i did", 0],
        ["*p", "i can’t believe i didn’t tell you...", 0],
        ["*p", "today’s actually the first day", 0],
        ["*p", "so i can’t talk for long.", 0],
        ["*p", "but thanks for checking up on me,,", 0],
        ["*p", "it’s not that sketchy i dont think,,", 0],
        ["*p", "is it?", 0],
        ["*p", "i havent ever heard of a job like this but they havent been weird", 0],
        ["*p", "yet,,,", 0],
        ["f", "that’s your first clue that its strange", 120],
        ["f", "why haven’t we heard about anything like this if its not sketchy ?", 120],
        ["f", "we are online most of the time…", 150],
        ["f", "even though its pretty sketchy", 100],
        ["f", "they don’t make you take an oath of silence or smth right ?", 250],
        ["f", "i just want you to be careful, this could be dangerous.", 250],
        ["*t", "…", 120],
        ["*t", "i guess they’re not wrong, i should be more careful", 250],
        ["f", "anyway i didn’t really mean to scare you,", 150],
        ["f", "even if its a little weird i trust your judgement", 100],
        ["f", "hoping you have a good day today ! kick ass out there !", 250],
        ["f", "i gotta get going too", 250],
        ["f", "my partner wanted to go out for breakfast today and", 250],
        ["f", "i woke up late lol", 0],
        ["*p", "thanks.. i really appreciate it.", 0, "finishedFirstConvoFriend"],
        ["*t", "since mom is being so annoying right now", 120],
        ["*p", "i’ll do my best! see you,, and have fun,,", 0],
        ["*w", "", 0]
    ],

    "d1_kcC" : [
        ["kc", "the system is ready now. i am ready to send you your first client", 300], 
        ["kc", "good luck.", 100, "sendFirstClient"], 
        ["*p", "thank you.", 0],
        ["*w", "", 0],
    ], 

    "d1_fjA" : [
        ["fj", "Hello?", 0], 
        ["fj", "I am FELIX JOEL.", 120], 
        ["*p", "This is The Wing. How may I help you?", 0],
        ["fj", "So...", 80],
        ["fj", "There's this girl :)", 80],
        ["fj", "And", 40],
        ["fj", "I", 20],
        ["fj", "CANNOT mess this up.", 80],
        ["*p", "", 0, "", "What's her name?|Could you elaborate?", 0],
        ["fj", "T R I S H she's so pretty and nice and I can't", 180],
        ["fj", "I can't stop THINKING about her!!", 100],
        ["fj", "I've already submitted her account and stuff, so... you got", 240],
        ["fj", "that already", 0],
        ["*p", "What does she like? Any other information you could give me?", 0], 
        ["fj", "Huhhhh...", 140],
        ["fj", "That's a hard one, Wing.", 200],
        ["fj", "She's so quiet all the time.", 120],
        ["fj", "Uhh...", 60],
        ["fj", "I'm a coffee man myself but I'm pretty sure she likes tea.", 120],
        ["fj", "Also, she's really shy, so talk about interests first! not LOOKS!", 120], 
        ["fj", "That's all I got.", 180],
        ["fj", "Keep me posted, Wing", 60, "finishedFirstConvoFelix"],
        ["*p", "Understood.", 0],
        ["*w", "", 0],
    ],
    
    "d1_tpA" : [
        ["*p", "hey there.", 0], 
        ["tp", "hi.", 300],
        ["*p", "your profile says you like tea.", 0],
        ["*p", "", 0, "tpA_openingLine", "tell me about it|i think you're beauTEAful."],
        ["*w", "", 0],
    ],
    
    "d1_tpB0" : [
        ["tp", "yikes.", 300, "endOfDemo",],
        ["*b", "", 60],
    ],
    
    "d1_tpB1" : [
        ["tp", "oh, I'd love to.", 300, "endOfDemo",],
        ["*w", "", 0],
    ],

    "d1_endOfDemo" : [
        ["kc", "----------------------------", 300],
        ["kc", "Thank you for reaching the end of the demo.", 0],
        ["kc", "Stay tuned for more!", 60],
        ["*w", "", 0],
    ],
    
    "d1_tp" : [
        ["tp", "test", 100],
        ["*p", "test", 0], 
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["*p", "test", 0], 
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["tp", "test", 100],
        ["*p", "test", 0], 
    ],

    
}